### PR TITLE
Fix Music Search - added support to api.vk.com and json data retrieve

### PR DESCRIPTION
**Pull request by black2279**
I temporarily solved the problem of research.
To do that I added in the code a request to vk.com's api and a way to manipulate JSON objects.
The proper functioning of this change depends only on the duration of the token that I get and if my account will not banned
Check if this change work for you.
Thanks

### CODE REVIEW

**Comment by jonkoops** [comment]
Thanks for your pull request, I will try to find some time to review it soon.

**Comment by vever001** [comment]
Hello there,

I believe it won't work because the access token is valid for a limited period of time. See https://vk.com/dev/authcode_flow_user --> point 4 expires_in
From my tests it is usually set to 86400 which means the token expires after 1 day.

I just spent some time today on fixing the app using vknet.
See my pull request: https://github.com/jonkoops/pirate/pull/66
Feel free to test.

Sincerely,
Hervé

**Comment by black2279** [comment]
Hello @vever001,
I update the token this morning because it was expired. 
To get the new token I edit the request and in the parameter  "scope=" I don't use only "audio" but "audio,offline". The answer on parameter "expires_in" was "0" and I think it is a free time token.
It is possible to verify it tomorrow.

I will test your pull request tomorrow.
Thanks

**Comment by jonkoops** [comment]
Closing this in favor of #66.

**Pull request closed without merging**
