### PR TITLE
Fix PirateApp using POST requests to https://vk.com/al_audio.php

### PR DESCRIPTION
**Pull request by vever001**
All Audio API methods have been shut down https://vk.com/dev/audio_api

### CODE REVIEW

**Comment by jonkoops** [comment]
LGTM!

**Comment by jonkoops** [comment]
@vever001 Would you be so kind to build and release me a new version? I believe you have the permissions necessary.

**Comment by KurtDeGreeff** [comment]
Hi, I tried to help and compiled the master branch but got error when during to login, is not accepting my vk credentials, any idea? The credentials are working fine when logging on the website

**Comment by jparkerweb** [comment]
strange.. I was able to build and then use the compiled .exe without issue.  Used VS2015 Pro to build.
"\pirate-master\Pirate\bin\Debug\Pirate.exe"

**Comment by jonkoops** [comment]
@KurtDeGreeff Got 2-step verification enabled by any chance?

**Comment by KurtDeGreeff** [comment]
No, don't have 2factor authentication enabled. Just recloned source and rebuild but still got same error below. Don't have enough experience to debug and resolve this.. Other ideas?
image

**Comment by wimpyrbx** [comment]
any chance this will be released with fix fully compiled?

**Comment by jonkoops** [comment]
@vever001 I am able to log in, but when I search there are never any results. Any chance you can take a look at that?

**Comment by walkthe** [comment]
just waiting for further info

**Pull request merged**
